language:   cpp
compiler:   g++

addons:
    apt:
        packages:
            - libunittest++-dev
            - valgrind

before_install:
    - wget --spider -q http://huckleberry.mhu.edu/cs220/unittest_ll.cpp; if [ $? -eq 0 ]; then echo "Download the new unittest_ll.cpp"; rm unittest_ll.cpp; wget http://huckleberry.mhu.edu/cs220/unittest_ll.cpp; else echo "No unittest_ll.cpp found"; fi

script: 
    - make
    - echo "1 2 3 4 5 -1" | ./linkedList
    - make travis 
    - ./test
    - valgrind --leak-check=full --error-exitcode=1 ./test

notifications:
    email: false
